### ISSUE TITLE
Add proper semver tag

### ISSUE THREAD

**Issue by tryffel** [Anderson-Lu/gofasion#3]
This is because go modules cannot utilize tags if they aren't properly semver tagged in the form of "v0.0.0". (https://github.com/golang/go/wiki/Modules#semantic-import-versioning)

**Comment by Anderson-Lu** [comment]
See here [https://github.com/Anderson-Lu/gofasion/commit/41a7982c9b5fab7ecbb5e2d0c19fc70b2f6af11e](https://github.com/Anderson-Lu/gofasion/commit/41a7982c9b5fab7ecbb5e2d0c19fc70b2f6af11e)
